CLASS zcl_mvc_sc0110_model DEFINITION INHERITING FROM zcl_mvc_root_model
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_mvc_sc0110_model IMPLEMENTATION.
ENDCLASS.
